version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /project/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /project/docker-credentials/password
    DOCKER_REGISTRY_URL: /project/docker-credentials/url

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "docker logging"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - echo "docker build"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/flask-app:latest" .
      - echo "build completed now pushing image to DOCKER_REGISTRY_URL"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/flask-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - 'scripts/*'
  base-directory: .

